// auto-generated companion: regenerates teenieping_data.js and pokemon_data.js
// run: node build_data.mjs   (from inside the clock_twins folder)
import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

// ── 티니핑 ──
const TEENIEPING_DIR = 'img_teenieping';
const teenieAll = readdirSync(TEENIEPING_DIR)
  .map(f => ({ f, m: f.match(/^TP-(\d{3})_(.+)\.webp$/) }))
  .filter(x => x.m)
  .map(({ f, m }) => ({
    no: parseInt(m[1], 10),
    name: m[2],
    file: `${TEENIEPING_DIR}/${f}`,
  }))
  .sort((a, b) => a.no - b.no);

const TEENIE_BASIC_NAMES = [
  '하츄핑', '나그네핑', '사뿐핑', '왕자핑', '아름핑', '트롯핑',
  '뽀니핑', '깨굴핑', '이클립스핑', '젠틀핑', '다이아나핑', '샤를핑',
];
const basicTeenieping = TEENIE_BASIC_NAMES.map((n, i) => {
  const c = teenieAll.find(x => x.name === n);
  if (!c) throw new Error('missing teenieping ' + n);
  return { hour: i + 1, name: c.name, file: c.file };
});

const teenieOut = teenieAll.map(({ no, ...rest }) => rest);
writeFileSync(
  'teenieping_data.js',
  `// auto-generated by build_data.mjs — do not edit by hand\n` +
  `var basicTeenieping = ${JSON.stringify(basicTeenieping, null, 2)};\n` +
  `var allTeenieping = ${JSON.stringify(teenieOut)};\n`
);

// ── 포켓몬 ──
const POK_DIR = 'img_pokemon';
const pokAll = [];
for (const genDir of readdirSync(POK_DIR)) {
  const genMatch = genDir.match(/^(\d+)세대$/);
  if (!genMatch) continue;
  const gen = parseInt(genMatch[1], 10);
  for (const f of readdirSync(path.join(POK_DIR, genDir))) {
    const m = f.match(/^포켓몬이미지_(\d{4})_(.+)\.webp$/);
    if (!m) continue;
    pokAll.push({
      name: m[2],
      file: `${POK_DIR}/${genDir}/${f}`,
      dex: parseInt(m[1], 10),
      gen,
    });
  }
}
pokAll.sort((a, b) => a.dex - b.dex);

const POK_BASIC_DEX = [25, 150, 151, 249, 250, 384, 445, 658, 716, 791, 888, 1007];
const basicPokemon = POK_BASIC_DEX.map((d, i) => {
  const c = pokAll.find(x => x.dex === d);
  if (!c) throw new Error('missing dex ' + d);
  return { hour: i + 1, name: c.name, file: c.file };
});

// ── 세대별 그룹 ──
const byGen = {};
for (const c of pokAll) {
  (byGen[c.gen] = byGen[c.gen] || []).push(c);
}

// 1) 가벼운 인덱스: 세대 카운트 + 큐레이션 12마리만
const genIndex = Object.keys(byGen)
  .map(Number)
  .sort((a, b) => a - b)
  .map(g => ({ gen: g, count: byGen[g].length }));

writeFileSync(
  'pokemon_data.js',
  `// auto-generated by build_data.mjs — do not edit by hand\n` +
  `// 세대별 데이터는 별도 pokemon_gen{N}.js에서 동적 로드\n` +
  `var basicPokemon = ${JSON.stringify(basicPokemon, null, 2)};\n` +
  `var pokemonGenIndex = ${JSON.stringify(genIndex)};\n`
);

// 2) 세대별 데이터 파일
let totalGenBytes = 0;
for (const [gen, list] of Object.entries(byGen)) {
  const fileName = `pokemon_gen${gen}.js`;
  const content =
    `// auto-generated by build_data.mjs — do not edit by hand\n` +
    `window.__pokemonGen = window.__pokemonGen || {};\n` +
    `window.__pokemonGen[${gen}] = ${JSON.stringify(list)};\n`;
  writeFileSync(fileName, content);
  totalGenBytes += content.length;
}

console.log(`teenieping: basic=${basicTeenieping.length}, all=${teenieAll.length}`);
console.log(`pokemon:    basic=${basicPokemon.length}, all=${pokAll.length}`);
console.log(`pokemon gen files: ${Object.keys(byGen).length} files, ${totalGenBytes} bytes total`);
