// auto-generated companion: regenerates teenieping_data.js and pokemon_data.js
// run: node build_data.mjs   (from inside the clock_twins folder)
import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

// ── 티니핑 메타 (teenieping_list.xlsx 기반) ──
// 기수별 [시작, 끝] 일련번호 + 로열/레전드 일련번호. 나머지는 '일반'.
const TEENIE_GROUPS = [
  { gen: 1, kind: '큐브 티니핑',          range: [1, 45],   royal: [1, 2, 3, 4, 5, 6], legend: [] },
  { gen: 2, kind: '보석 티니핑',          range: [46, 65],  royal: [46, 47, 48],       legend: [] },
  { gen: 3, kind: '열쇠 티니핑',          range: [66, 85],  royal: [66, 67, 68],       legend: [69] },
  { gen: 4, kind: '디저트 티니핑',        range: [86, 106], royal: [86, 87, 88],       legend: [89, 90] },
  { gen: 5, kind: '스타 티니핑',          range: [107, 129],royal: [107, 108, 109, 110], legend: [111] },
  { gen: 6, kind: '프린세스&프린스 티니핑',range: [131, 150],royal: [131, 132, 133],    legend: [134, 135] },
];
const TEENIE_SPECIAL = new Set([130, 151]); // 특별 등급

function teenieMeta(no) {
  if (TEENIE_SPECIAL.has(no)) {
    return { gen: 0, kind: '특별 티니핑', tier: '특별' };
  }
  for (const g of TEENIE_GROUPS) {
    if (no >= g.range[0] && no <= g.range[1]) {
      let tier = '일반';
      if (g.royal.includes(no)) tier = '로열';
      else if (g.legend.includes(no)) tier = '레전드';
      return { gen: g.gen, kind: g.kind, tier };
    }
  }
  return { gen: 0, kind: '특별 티니핑', tier: '특별' };
}

// ── 티니핑 ──
const TEENIEPING_DIR = 'img_teenieping';
const teenieAll = readdirSync(TEENIEPING_DIR)
  .map(f => ({ f, m: f.match(/^TP-(\d{3})_(.+)\.webp$/) }))
  .filter(x => x.m)
  .map(({ f, m }) => {
    const no = parseInt(m[1], 10);
    const meta = teenieMeta(no);
    return {
      no,
      name: m[2],
      file: `${TEENIEPING_DIR}/${f}`,
      gen: meta.gen,
      kind: meta.kind,
      tier: meta.tier,
    };
  })
  .sort((a, b) => a.no - b.no);

const TEENIE_BASIC_NAMES = [
  '하츄핑', '나그네핑', '사뿐핑', '왕자핑', '아름핑', '트롯핑',
  '뽀니핑', '깨굴핑', '이클립스핑', '젠틀핑', '다이아나핑', '샤를핑',
];
const basicTeenieping = TEENIE_BASIC_NAMES.map((n, i) => {
  const c = teenieAll.find(x => x.name === n);
  if (!c) throw new Error('missing teenieping ' + n);
  return { hour: i + 1, name: c.name, file: c.file, tier: c.tier };
});

// 런타임에는 no를 그대로 노출(도감 정렬·식별용으로 유용).
const teenieOut = teenieAll;
writeFileSync(
  'teenieping_data.js',
  `// auto-generated by build_data.mjs — do not edit by hand\n` +
  `var basicTeenieping = ${JSON.stringify(basicTeenieping, null, 2)};\n` +
  `var allTeenieping = ${JSON.stringify(teenieOut)};\n`
);

// ── 포켓몬 ──
const POK_DIR = 'img_pokemon';
const pokAll = [];
for (const genDir of readdirSync(POK_DIR)) {
  const genMatch = genDir.match(/^(\d+)세대$/);
  if (!genMatch) continue;
  const gen = parseInt(genMatch[1], 10);
  for (const f of readdirSync(path.join(POK_DIR, genDir))) {
    const m = f.match(/^포켓몬이미지_(\d{4})_(.+)\.webp$/);
    if (!m) continue;
    pokAll.push({
      name: m[2],
      file: `${POK_DIR}/${genDir}/${f}`,
      dex: parseInt(m[1], 10),
      gen,
    });
  }
}
pokAll.sort((a, b) => a.dex - b.dex);

// 큐레이션: 극장판 "뮤츠의 역습 EVOLUTION" 주역 포켓몬
// hour 1=뮤츠, 2=뮤, 3=피카츄, 4=리자몽, 5=거북왕, 6=이상해꽃,
// 7=잠만보, 8=라프라스, 9=팬텀, 10=후딘, 11=니드킹, 12=스라크
const POK_BASIC_DEX = [150, 151, 25, 6, 9, 3, 143, 131, 94, 65, 34, 123];
const basicPokemon = POK_BASIC_DEX.map((d, i) => {
  const c = pokAll.find(x => x.dex === d);
  if (!c) throw new Error('missing dex ' + d);
  return { hour: i + 1, name: c.name, file: c.file };
});

// ── 세대별 그룹 ──
const byGen = {};
for (const c of pokAll) {
  (byGen[c.gen] = byGen[c.gen] || []).push(c);
}

// 1) 가벼운 인덱스: 세대 카운트 + 큐레이션 12마리만
const genIndex = Object.keys(byGen)
  .map(Number)
  .sort((a, b) => a - b)
  .map(g => ({ gen: g, count: byGen[g].length }));

writeFileSync(
  'pokemon_data.js',
  `// auto-generated by build_data.mjs — do not edit by hand\n` +
  `// 세대별 데이터는 별도 pokemon_gen{N}.js에서 동적 로드\n` +
  `var basicPokemon = ${JSON.stringify(basicPokemon, null, 2)};\n` +
  `var pokemonGenIndex = ${JSON.stringify(genIndex)};\n`
);

// 2) 세대별 데이터 파일
let totalGenBytes = 0;
for (const [gen, list] of Object.entries(byGen)) {
  const fileName = `pokemon_gen${gen}.js`;
  const content =
    `// auto-generated by build_data.mjs — do not edit by hand\n` +
    `window.__pokemonGen = window.__pokemonGen || {};\n` +
    `window.__pokemonGen[${gen}] = ${JSON.stringify(list)};\n`;
  writeFileSync(fileName, content);
  totalGenBytes += content.length;
}

console.log(`teenieping: basic=${basicTeenieping.length}, all=${teenieAll.length}`);
console.log(`pokemon:    basic=${basicPokemon.length}, all=${pokAll.length}`);
console.log(`pokemon gen files: ${Object.keys(byGen).length} files, ${totalGenBytes} bytes total`);
