// SKZ 시계 — Stray Kids 8 멤버 + SKZOO 8 캐릭터 (총 16) 데이터
// kind: '멤버' | 'SKZOO'  ·  tier: 멤버는 데뷔 순서대로 '리더'/'보컬'/'래퍼'/'댄서' 등 칩,
// SKZOO는 동물 종류 칩
// pairWith: 멤버 ↔ SKZOO 1:1 매칭 (영문명으로 조인) — 도감 '페어' 모드에서 활용
var allSkz = [
  // ── 멤버 8명 (데뷔 순서) ──
  { no: 1, name: '방찬', en: 'Bang Chan',  kind: '멤버',
    file: 'img_skz/SKZ-01_방찬.webp',
    role: '리더 · 메인보컬 · 메인래퍼', birthYear: 1997, origin: '호주',
    pairWith: '울프찬',
    blurb: '리더 형아! 호주에서 자랐어요. 노래도 만들 줄 알아요.' },
  { no: 2, name: '리노', en: 'Lee Know',   kind: '멤버',
    file: 'img_skz/SKZ-02_리노.webp',
    role: '메인댄서 · 서브보컬', birthYear: 1998, origin: '한국',
    pairWith: '리빗',
    blurb: '춤을 정말 잘 추는 형아예요. 고양이 세 마리를 키우는 다정한 집사.' },
  { no: 3, name: '창빈', en: 'Changbin',   kind: '멤버',
    file: 'img_skz/SKZ-03_창빈.webp',
    role: '메인래퍼 · 작곡', birthYear: 1999, origin: '한국',
    pairWith: '돼끼',
    blurb: '랩이 빠르고 힘 센 형아. 키는 작지만 어깨가 정말 넓어요.' },
  { no: 4, name: '현진', en: 'Hyunjin',    kind: '멤버',
    file: 'img_skz/SKZ-04_현진.webp',
    role: '메인댄서 · 래퍼', birthYear: 2000, origin: '한국',
    pairWith: '지니렛',
    blurb: '춤·그림·디자인 모두 잘하는 멋쟁이 오빠.' },
  { no: 5, name: '한',   en: 'HAN',        kind: '멤버',
    file: 'img_skz/SKZ-05_한.webp',
    role: '메인래퍼 · 메인보컬 · 작곡', birthYear: 2000, origin: '한국',
    pairWith: '한쿼카',
    blurb: '랩도 노래도 작곡도 모두 잘하는 다재다능 오빠.' },
  { no: 6, name: '필릭스', en: 'Felix',    kind: '멤버',
    file: 'img_skz/SKZ-06_필릭스.webp',
    role: '메인댄서 · 래퍼', birthYear: 2000, origin: '호주',
    pairWith: '뽁아리',
    blurb: '주근깨 가득한 호주 오빠. 목소리가 정말 정말 낮아요.' },
  { no: 7, name: '승민', en: 'Seungmin',   kind: '멤버',
    file: 'img_skz/SKZ-07_승민.webp',
    role: '메인보컬', birthYear: 2000, origin: '한국',
    pairWith: '퍼핌',
    blurb: '노래를 가장 잘 부르는 오빠. 강아지처럼 활달해요.' },
  { no: 8, name: '아이엔', en: 'I.N',      kind: '멤버',
    file: 'img_skz/SKZ-08_아이엔.webp',
    role: '서브보컬 · 막내', birthYear: 2001, origin: '한국',
    pairWith: '폭시니',
    blurb: '귀여운 막내 오빠. 형들 사이에서 사랑을 듬뿍 받아요.' },

  // ── SKZOO 8마리 (멤버별 동물 캐릭터) ──
  { no: 9, name: '울프찬', en: 'Wolf Chan', kind: 'SKZOO',
    file: 'img_skz/SKZ-09_울프찬.webp',
    species: '늑대', color: '회색·하양',
    pairWith: '방찬',
    blurb: '리더 늑대! 무리를 따뜻하게 이끌어요. 호주에서 자란 형 늑대예요.' },
  { no: 10, name: '리빗', en: 'Leebit',    kind: 'SKZOO',
    file: 'img_skz/SKZ-10_리빗.webp',
    species: '토끼', color: '하양',
    pairWith: '리노',
    blurb: '춤추는 하얀 토끼. 톡톡 튀는 발 동작이 멋져요.' },
  { no: 11, name: '돼끼', en: 'DWAEKKI',   kind: 'SKZOO',
    file: 'img_skz/SKZ-11_돼끼.webp',
    species: '돼지+토끼', color: '분홍',
    pairWith: '창빈',
    blurb: '자기를 토끼라고 믿는 작은 분홍 돼지. 어깨가 진짜 넓어요!' },
  { no: 12, name: '지니렛', en: 'Jiniret', kind: 'SKZOO',
    file: 'img_skz/SKZ-12_지니렛.webp',
    species: '페렛', color: '하양',
    pairWith: '현진',
    blurb: '눈이 동그란 하얀 페렛. 그림 그리기를 좋아해요.' },
  { no: 13, name: '한쿼카', en: 'HAN QUOKKA', kind: 'SKZOO',
    file: 'img_skz/SKZ-13_한쿼카.webp',
    species: '쿼카', color: '주황·노랑',
    pairWith: '한',
    blurb: '쿼카 친구! 세상에서 가장 행복한 동물이에요.' },
  { no: 14, name: '뽁아리', en: 'BbokAri', kind: 'SKZOO',
    file: 'img_skz/SKZ-14_뽁아리.webp',
    species: '병아리', color: '노랑',
    pairWith: '필릭스',
    blurb: '눈이 반짝반짝 큰 노란 병아리. 주근깨가 살짝 있어요.' },
  { no: 15, name: '퍼핌', en: 'PuppyM',    kind: 'SKZOO',
    file: 'img_skz/SKZ-15_퍼핌.webp',
    species: '강아지', color: '베이지',
    pairWith: '승민',
    blurb: '귀가 살짝 늘어진 노란 강아지. 노래하기를 좋아해요.' },
  { no: 16, name: '폭시니', en: 'FoxI.Ny', kind: 'SKZOO',
    file: 'img_skz/SKZ-16_폭시니.webp',
    species: '여우', color: '베이지·분홍',
    pairWith: '아이엔',
    blurb: '귀가 큰 작은 사막여우. 막내답게 애교가 많아요.' },
];

// 페어 매핑 헬퍼: 한 캐릭터의 짝(멤버↔SKZOO)을 찾아 반환
function findSkzPair(c) {
  if (!c || !c.pairWith) return null;
  for (var i = 0; i < allSkz.length; i++) {
    if (allSkz[i].name === c.pairWith) return allSkz[i];
  }
  return null;
}
